name: neoflex_quest
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  postgres: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/animations/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/static/Montserrat-Italic.ttf
          style: italic
